parameters:
  - name: dependsOn
    type: object
    default: []
  - name: azureSubscription
    type: string
  - name: environment
    type: string
  - name: environmentName
    type: string

jobs:
  - deployment: validate_bicep_against_${{ parameters.environmentName }}_environment
    dependsOn: ${{ parameters.dependsOn }}
    environment: ${{ parameters.environment }}

    workspace:
      clean: all

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              name: RunPreflightValidation
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: "pscore"
                scriptLocation: "inlineScript"
                inlineScript: |
                  $config = (Get-Content params/${{ parameters.environmentName }}.json | ConvertFrom-Json)

                  az deployment sub validate `
                    --name "portal-web-$($config.parameters.environment.value)-$($config.parameters.instance.value)" `
                    --template-file bicep/main.bicep `
                    --location $config.parameters.location.value `
                    --parameters @params/$($config.parameters.environment.value).json `
                        keyVaultCreateMode='recover'

            - task: AzureCLI@2
              name: RunWhatIfDeploy
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: "pscore"
                scriptLocation: "inlineScript"
                inlineScript: |
                  az deployment sub what-if `
                    --name "portal-web-$($config.parameters.environment.value)-$($config.parameters.instance.value)" `
                    --template-file bicep/main.bicep `
                    --location $config.parameters.location.value `
                    --parameters @params/$($config.parameters.environment.value).json
