parameters:
- name: jobName
  type: string
  default: DeploySqlDatabase
- name: dependsOn
  type: object
  default: []
- name: environmentServiceNameAzureRM
- name: serverName
  type: string
  default: ""
- name: databaseName
  type: string
  default: ""
- name: sqlCmdArgs
  type: string
  default: ""

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}
  
  steps: 
    - download: current
      displayName: 'Download database artifact'
      artifact: database

    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: '${{ parameters.environmentServiceNameAzureRM }}'
        ServerName: '${{ parameters.serverName }}'
        DatabaseName: '${{ parameters.databaseName }}'
        AuthenticationType: servicePrincipal
        DacpacFile: '$(Pipeline.Workspace)/database/database.dacpac'
        AdditionalArguments: ${{ parameters.sqlCmdArgs }}
