parameters:
- name: jobName
  type: string
  default: DeploySqlDatabase
- name: dependsOn
  type: object
  default: []
- name: environmentServiceNameAzureRM
- name: sqlCmdArgs
  type: string
  default: ""

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}

  variables:
  - name: sql_server_domain_name
    value: $[ dependencies.TerraformPlanAndApply.outputs['terraform_output.sql_server_domain_name'] ]
  - name: sql_database_name
    value: $[ dependencies.TerraformPlanAndApply.outputs['terraform_output.sql_database_name'] ]

  steps: 
    - download: current
      displayName: 'Download database artifact'
      artifact: database

    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: '${{ parameters.environmentServiceNameAzureRM }}'
        ServerName: '$(sql_server_domain_name)'
        DatabaseName: '$(sql_database_name)'
        AuthenticationType: servicePrincipal
        DacpacFile: '$(Pipeline.Workspace)/database/database.dacpac'
        AdditionalArguments: ${{ parameters.sqlCmdArgs }}
