parameters:
- name: azureSubscription
  type: string
- name: environment
  type: string
- name: environmentName
  type: string
- name: environmentTag
  type: string
- name: webAppsAzureSubscription
  type: string
- name: webAppsEnvironment
  type: string
- name: webAppsResourceGroup
  type: string
- name: blueGreenDeploy
  type: boolean
  default: false


stages:
- stage: Deploy${{ parameters.environmentName }}
  jobs:

  - job: Deploy${{ parameters.environmentName }}AADResources

    workspace:
      clean: all

    steps:
      - task: AzureCLI@2
        displayName: SetDeployPrincipalPermissions
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"${{ parameters.environmentTag }}"'
          addSpnToEnvironment: true
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/CreateDatabaseAADGroups.ps1'

  - deployment: Deploy${{ parameters.environmentName }}PlatformBicep
    dependsOn: ['Deploy${{ parameters.environmentName }}AADResources']
    environment: ${{ parameters.environment }}

    workspace:
      clean: all

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: Deploy${{ parameters.environmentName }}PlatformBicep
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location uksouth `
                    --parameters @params/platform.${{ parameters.environmentTag }}.json


  - job: Deploy${{ parameters.environmentName }}PlatformPermissions
    dependsOn: ['Deploy${{ parameters.environmentName }}PlatformBicep']

    workspace:
      clean: all

    steps:
      - task: AzureCLI@2
        displayName: SetDeployPrincipalPermissions
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"${{ parameters.environmentTag }}" "uksouth"'
          addSpnToEnvironment: true
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetDeployPrincipalPermissions.ps1'

      - task: AzureCLI@2
        displayName: CreateAppRegistrations
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"${{ parameters.environmentTag }}" "uksouth"'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/CreateAppRegistrations.ps1'

      - task: AzureCLI@2
        displayName: CreateAppRegistrationsCredentials
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"${{ parameters.environmentTag }}" "uksouth"'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/CreateAppRegistrationsCredentials.ps1'

  - deployment: Deploy${{ parameters.environmentName }}ServicesBicep
    dependsOn: ['Deploy${{ parameters.environmentName }}PlatformPermissions']
    environment: ${{ parameters.environment }}

    workspace:
      clean: all

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: Deploy${{ parameters.environmentName }}ServicesBicep
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  $eventsApiAppName = "portal-events-api-${{ parameters.environmentTag }}"
                  $repositoryApiName = "portal-repository-api-${{ parameters.environmentTag }}"
                  $serversApiName = "portal-servers-api-${{ parameters.environmentTag }}"

                  $repositoryApiAppId = (az ad app list --filter "displayName eq '$repositoryApiName'" --query '[].appId') | ConvertFrom-Json
                  $eventsApiAppId = (az ad app list --filter "displayName eq '$eventsApiAppName'" --query '[].appId') | ConvertFrom-Json
                  $serversApiAppId = (az ad app list --filter "displayName eq '$serversApiName'" --query '[].appId') | ConvertFrom-Json

                  az deployment group create --resource-group "rg-portal-${{ parameters.environmentTag }}-uksouth" `
                      --template-file bicep/services.bicep `
                      --parameters @params/services.${{ parameters.environmentTag }}.json `
                      parEventsApiAppId=$eventsApiAppId `
                      parRepositoryApiAppId=$repositoryApiAppId `
                      parServersApiAppId=$serversApiAppId 

  - job: Deploy${{ parameters.environmentName }}ServicesPermissions
    dependsOn: ['Deploy${{ parameters.environmentName }}ServicesBicep']

    workspace:
      clean: all

    steps:
      - task: AzureCLI@2
        displayName: SetB3BotsClientAppPermissions
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '${{ parameters.environmentTag }}'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetB3BotsClientAppPermissions.ps1'

      - task: AzureCLI@2
        displayName: SetIngestApiFuncAppPermissions
        inputs:
          azureSubscription: ${{ parameters.webAppsAzureSubscription }}
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '${{ parameters.environmentTag }}'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetIngestApiFuncAppPermissions.ps1'

      - task: AzureCLI@2
        displayName: SetRepositoryApiAppPermissions
        inputs:
          azureSubscription: ${{ parameters.webAppsAzureSubscription }}
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '${{ parameters.environmentTag }}'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetRepositoryApiAppPermissions.ps1'

      - task: AzureCLI@2
        displayName: SetRepositoryAppPermissions
        inputs:
          azureSubscription: ${{ parameters.webAppsAzureSubscription }}
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '${{ parameters.environmentTag }}'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetRepositoryAppPermissions.ps1'

      - task: AzureCLI@2
        displayName: SetServersWebApiPermissions
        inputs:
          azureSubscription: ${{ parameters.webAppsAzureSubscription }}
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '${{ parameters.environmentTag }}'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetServersWebApiPermissions.ps1'

      - task: AzureCLI@2
        displayName: SetAdminWebAppPermissions
        inputs:
          azureSubscription: ${{ parameters.webAppsAzureSubscription }}
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '${{ parameters.environmentTag }}'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetAdminWebAppPermissions.ps1'

      - task: AzureCLI@2
        displayName: SetSyncAppPermissions
        inputs:
          azureSubscription: ${{ parameters.webAppsAzureSubscription }}
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '${{ parameters.environmentTag }}'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetSyncAppPermissions.ps1'

  - template: jobs/deploy-sql-database.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['Deploy${{ parameters.environmentName }}ServicesPermissions']
      jobName: Deploy${{ parameters.environmentName }}SqlDatabase
      serverName: "sql-platform-${{ parameters.environmentTag }}-uksouth.database.windows.net"
      databaseName: 'portaldb-${{ parameters.environmentTag }}'
      subscription: ${{ parameters.azureSubscription }}
      sqlCmdArgs: '/Variables:env=${{ parameters.environmentTag }}'

  - template: jobs/deploy-web-app.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['Deploy${{ parameters.environmentName }}SqlDatabase']
      environment: ${{ parameters.webAppsEnvironment }}
      projectName: repository-webapi
      jobName: Deploy${{ parameters.environmentName }}RepositoryWebApi
      webAppName: "webapi-repository-portal-${{ parameters.environmentTag }}-uksouth"
      webAppNameResourceGroup: ${{ parameters.webAppsResourceGroup }}
      subscription: ${{ parameters.webAppsAzureSubscription }}
      blueGreenDeploy: ${{ parameters.blueGreenDeploy }}

  - template: jobs/deploy-function-app.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['Deploy${{ parameters.environmentName }}RepositoryWebApi']
      environment: ${{ parameters.webAppsEnvironment }}
      projectName: repository-func
      jobName: Deploy${{ parameters.environmentName }}RepositoryFunctionApp
      functionAppName: "fn-repository-portal-${{ parameters.environmentTag }}-uksouth"
      functionAppResourceGroup: ${{ parameters.webAppsResourceGroup }}
      subscription: ${{ parameters.webAppsAzureSubscription }}

  - template: jobs/deploy-function-app.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['Deploy${{ parameters.environmentName }}RepositoryWebApi']
      environment: ${{ parameters.webAppsEnvironment }}
      projectName: ingest-func
      jobName: Deploy${{ parameters.environmentName }}IngestFunctionApp
      functionAppName: "fn-ingest-portal-${{ parameters.environmentTag }}-uksouth"
      functionAppResourceGroup: ${{ parameters.webAppsResourceGroup }}
      subscription: ${{ parameters.webAppsAzureSubscription }}

  - template: jobs/deploy-function-app.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['Deploy${{ parameters.environmentName }}RepositoryWebApi']
      environment: ${{ parameters.webAppsEnvironment }}
      projectName: events-func
      jobName: Deploy${{ parameters.environmentName }}EventsFunctionApp
      functionAppName: "fn-events-portal-${{ parameters.environmentTag }}-uksouth"
      functionAppResourceGroup: ${{ parameters.webAppsResourceGroup }}
      subscription: ${{ parameters.webAppsAzureSubscription }}
      blueGreenDeploy: ${{ parameters.blueGreenDeploy }}

  - template: jobs/deploy-function-app.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['Deploy${{ parameters.environmentName }}RepositoryWebApi']
      environment: ${{ parameters.webAppsEnvironment }}
      projectName: sync-func
      jobName: Deploy${{ parameters.environmentName }}SyncFunctionApp
      functionAppName: "fn-sync-portal-${{ parameters.environmentTag }}-uksouth"
      functionAppResourceGroup: ${{ parameters.webAppsResourceGroup }}
      subscription: ${{ parameters.webAppsAzureSubscription }}

  - template: jobs/deploy-web-app.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['Deploy${{ parameters.environmentName }}RepositoryWebApi']
      environment: ${{ parameters.webAppsEnvironment }}
      projectName: servers-webapi
      jobName: Deploy${{ parameters.environmentName }}ServersWebApi
      webAppName: "webapi-servers-portal-${{ parameters.environmentTag }}-uksouth"
      webAppNameResourceGroup: ${{ parameters.webAppsResourceGroup }}
      subscription: ${{ parameters.webAppsAzureSubscription }}
      blueGreenDeploy: ${{ parameters.blueGreenDeploy }}

  - template: jobs/deploy-web-app.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['Deploy${{ parameters.environmentName }}RepositoryWebApi']
      environment: ${{ parameters.webAppsEnvironment }}
      projectName: admin-webapp
      jobName: Deploy${{ parameters.environmentName }}AdminWebApp
      webAppName: "webapp-admin-portal-${{ parameters.environmentTag }}-uksouth"
      webAppNameResourceGroup: ${{ parameters.webAppsResourceGroup }}
      subscription: ${{ parameters.webAppsAzureSubscription }}
      blueGreenDeploy: ${{ parameters.blueGreenDeploy }}

- stage: Destroy${{ parameters.environmentName }}ResourcesForCostAndPerformance
  jobs:

  - deployment: Destroy${{ parameters.environmentName }}ResourcesForCostAndPerformance
    environment: ${{ parameters.webAppsEnvironment }}

    workspace:
      clean: all

    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              displayName: Destroy${{ parameters.environmentName }}StagingSlots
              inputs:
                azureSubscription: ${{ parameters.webAppsAzureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az functionapp deployment slot delete --name "fn-events-portal-${{ parameters.environmentTag }}-uksouth" --resource-group ${{ parameters.webAppsResourceGroup }} --slot staging

                  az webapp deployment slot delete --name "webapi-repository-portal-${{ parameters.environmentTag }}-uksouth" --resource-group ${{ parameters.webAppsResourceGroup }} --slot staging
                  az webapp deployment slot delete --name "webapi-servers-portal-${{ parameters.environmentTag }}-uksouth" --resource-group ${{ parameters.webAppsResourceGroup }} --slot staging
                  az webapp deployment slot delete --name "webapp-admin-portal-${{ parameters.environmentTag }}-uksouth" --resource-group ${{ parameters.webAppsResourceGroup }} --slot staging
