parameters:
- name: jobName
  type: string
  default: DeployFunctionApp
- name: dependsOn
  type: object
  default: []
- name: projectName
  type: string
  default: 'function-app'
- name: functionAppName
  type: string
- name: environmentServiceNameAzureRM

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}

  steps: 
    - download: current
      displayName: 'Download ${{ parameters.projectName }} artifact'
      artifact: ${{ parameters.projectName }}

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: '${{ parameters.environmentServiceNameAzureRM }}'
        appName: '${{ parameters.functionAppName }}'
        package: '$(Pipeline.Workspace)/${{ parameters.projectName }}/${{ parameters.projectName }}.zip'