// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("AdminId", Name = "IX_Admin_Id")]
    [Index("PlayerPlayerId", Name = "IX_Player_PlayerId")]
    public partial class AdminAction
    {
        [Key]
        public Guid AdminActionId { get; set; }
        public int Type { get; set; }
        public string Text { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Expires { get; set; }
        [Column("Admin_Id")]
        [StringLength(128)]
        public string AdminId { get; set; }
        [Column("Player_PlayerId")]
        public Guid? PlayerPlayerId { get; set; }
        public int ForumTopicId { get; set; }

        [ForeignKey("AdminId")]
        [InverseProperty("AdminActions")]
        public virtual AspNetUser Admin { get; set; }
        [ForeignKey("PlayerPlayerId")]
        [InverseProperty("AdminActions")]
        public virtual Player PlayerPlayer { get; set; }
    }
}