// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("GameServerServerId", Name = "IX_GameServer_ServerId")]
    public partial class BanFileMonitor
    {
        [Key]
        public Guid BanFileMonitorId { get; set; }
        public string FilePath { get; set; }
        public long RemoteFileSize { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastSync { get; set; }
        public string LastError { get; set; }
        [Column("GameServer_ServerId")]
        public Guid? GameServerServerId { get; set; }

        [ForeignKey("GameServerServerId")]
        [InverseProperty("BanFileMonitors")]
        public virtual GameServer GameServerServer { get; set; }
    }
}