// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("GameServerServerId", Name = "IX_GameServer_ServerId")]
    [Index("PlayerPlayerId", Name = "IX_Player_PlayerId")]
    [Index("Timestamp", Name = "IX_Timestamp")]
    public partial class ChatLog
    {
        [Key]
        public Guid ChatLogId { get; set; }
        public string Username { get; set; }
        public int ChatType { get; set; }
        public string Message { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Timestamp { get; set; }
        [Column("GameServer_ServerId")]
        public Guid? GameServerServerId { get; set; }
        [Column("Player_PlayerId")]
        public Guid? PlayerPlayerId { get; set; }

        [ForeignKey("GameServerServerId")]
        [InverseProperty("ChatLogs")]
        public virtual GameServer GameServerServer { get; set; }
        [ForeignKey("PlayerPlayerId")]
        [InverseProperty("ChatLogs")]
        public virtual Player2 PlayerPlayer { get; set; }
    }
}