// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    public partial class Demo
    {
        [Key]
        public Guid DemoId { get; set; }
        public int Game { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        public string Map { get; set; }
        public string Mod { get; set; }
        public string GameType { get; set; }
        public string Server { get; set; }
        public long Size { get; set; }
        public Guid? UserProfileId { get; set; }
        public string DemoFileUri { get; set; }

        [ForeignKey("UserProfileId")]
        [InverseProperty("Demos")]
        public virtual UserProfile UserProfile { get; set; }
    }
}