// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("UserId", Name = "IX_User_Id")]
    public partial class Demo
    {
        [Key]
        public Guid DemoId { get; set; }
        public int Game { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        public string Map { get; set; }
        public string Mod { get; set; }
        public string GameType { get; set; }
        public string Server { get; set; }
        public long Size { get; set; }
        [Column("User_Id")]
        [StringLength(128)]
        public string UserId { get; set; }
        public string DemoFileUri { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Demos")]
        public virtual AspNetUser User { get; set; }
    }
}