// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    public partial class LivePlayerLocation
    {
        [Key]
        public Guid LivePlayerLocationId { get; set; }
        public string IpAddress { get; set; }
        public double Lat { get; set; }
        public double Long { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastSeen { get; set; }
    }
}