// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("GameServerServerId", Name = "IX_GameServer_ServerId")]
    public partial class LivePlayer
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(60)]
        public string Name { get; set; }
        public int Score { get; set; }
        public int Ping { get; set; }
        public int Num { get; set; }
        public int Rate { get; set; }
        [StringLength(10)]
        public string Team { get; set; }
        public TimeSpan Time { get; set; }
        [StringLength(60)]
        public string IpAddress { get; set; }
        public double? Lat { get; set; }
        public double? Long { get; set; }
        [StringLength(60)]
        public string CountryCode { get; set; }
        public int GameType { get; set; }
        [Column("GameServer_ServerId")]
        public Guid? GameServerServerId { get; set; }

        [ForeignKey("GameServerServerId")]
        [InverseProperty("LivePlayers")]
        public virtual GameServer GameServerServer { get; set; }
    }
}