// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("MapId", Name = "IX_MapId", IsUnique = true)]
    public partial class Map
    {
        public Map()
        {
            MapFiles = new HashSet<MapFile>();
            MapRotations = new HashSet<MapRotation>();
            MapVotes = new HashSet<MapVote>();
        }

        [Key]
        public Guid MapId { get; set; }
        public int GameType { get; set; }
        public string MapName { get; set; }

        [InverseProperty("MapMap")]
        public virtual ICollection<MapFile> MapFiles { get; set; }
        [InverseProperty("MapMap")]
        public virtual ICollection<MapRotation> MapRotations { get; set; }
        [InverseProperty("MapMap")]
        public virtual ICollection<MapVote> MapVotes { get; set; }
    }
}