// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("MapMapId", Name = "IX_Map_MapId")]
    public partial class MapFile
    {
        [Key]
        public Guid MapFileId { get; set; }
        public string FileName { get; set; }
        [Column("Map_MapId")]
        public Guid? MapMapId { get; set; }

        [ForeignKey("MapMapId")]
        [InverseProperty("MapFiles")]
        public virtual Map MapMap { get; set; }
    }
}