// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("GameServerServerId", Name = "IX_GameServer_ServerId")]
    [Index("MapMapId", Name = "IX_Map_MapId")]
    public partial class MapRotation
    {
        [Key]
        public Guid MapRotationId { get; set; }
        public string GameMode { get; set; }
        [Column("GameServer_ServerId")]
        public Guid? GameServerServerId { get; set; }
        [Column("Map_MapId")]
        public Guid? MapMapId { get; set; }

        [ForeignKey("GameServerServerId")]
        [InverseProperty("MapRotations")]
        public virtual GameServer GameServerServer { get; set; }
        [ForeignKey("MapMapId")]
        [InverseProperty("MapRotations")]
        public virtual Map MapMap { get; set; }
    }
}