// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("MapMapId", Name = "IX_Map_MapId")]
    [Index("PlayerPlayerId", Name = "IX_Player_PlayerId")]
    public partial class MapVote
    {
        [Key]
        public Guid MapVoteId { get; set; }
        public bool Like { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Timestamp { get; set; }
        [Column("Map_MapId")]
        public Guid? MapMapId { get; set; }
        [Column("Player_PlayerId")]
        public Guid? PlayerPlayerId { get; set; }

        [ForeignKey("MapMapId")]
        [InverseProperty("MapVotes")]
        public virtual Map MapMap { get; set; }
        [ForeignKey("PlayerPlayerId")]
        [InverseProperty("MapVotes")]
        public virtual Player PlayerPlayer { get; set; }
    }
}