// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("GameServerId", Name = "IX_GameServerId")]
    [Index("MapId", Name = "IX_MapId")]
    [Index("MapVoteId", Name = "IX_MapVoteId", IsUnique = true)]
    [Index("PlayerId", Name = "IX_PlayerId")]
    public partial class MapVote
    {
        [Key]
        public Guid MapVoteId { get; set; }
        public Guid MapId { get; set; }
        public Guid PlayerId { get; set; }
        public Guid? GameServerId { get; set; }
        public bool Like { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Timestamp { get; set; }

        [ForeignKey("GameServerId")]
        [InverseProperty("MapVotes")]
        public virtual GameServer GameServer { get; set; }
        [ForeignKey("MapId")]
        [InverseProperty("MapVotes")]
        public virtual Map Map { get; set; }
        [ForeignKey("PlayerId")]
        [InverseProperty("MapVotes")]
        public virtual Player Player { get; set; }
    }
}