// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("Address", Name = "IX_Address")]
    [Index("PlayerPlayerId", Name = "IX_Player_PlayerId")]
    public partial class PlayerIpAddress
    {
        [Key]
        public Guid PlayerIpAddressId { get; set; }
        [StringLength(60)]
        public string Address { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Added { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastUsed { get; set; }
        [Column("Player_PlayerId")]
        public Guid? PlayerPlayerId { get; set; }

        [ForeignKey("PlayerPlayerId")]
        [InverseProperty("PlayerIpAddresses")]
        public virtual Player2 PlayerPlayer { get; set; }
    }
}