// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace XtremeIdiots.Portal.DataLib
{
    public partial class PortalDbContext : DbContext
    {
        public PortalDbContext()
        {
        }

        public PortalDbContext(DbContextOptions<PortalDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AdminAction> AdminActions { get; set; }
        public virtual DbSet<BanFileMonitor> BanFileMonitors { get; set; }
        public virtual DbSet<ChatLog> ChatLogs { get; set; }
        public virtual DbSet<Demo> Demoes { get; set; }
        public virtual DbSet<DemoAuthKey> DemoAuthKeys { get; set; }
        public virtual DbSet<GameServer> GameServers { get; set; }
        public virtual DbSet<GameServerEvent> GameServerEvents { get; set; }
        public virtual DbSet<GameServerStat> GameServerStats { get; set; }
        public virtual DbSet<LivePlayer> LivePlayers { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<MapVote> MapVotes { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerAlias> PlayerAliases { get; set; }
        public virtual DbSet<PlayerIpAddress> PlayerIpAddresses { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserProfileClaim> UserProfileClaims { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=database;Integrated Security=true");

            modelBuilder.Entity<AdminAction>(entity =>
            {
                entity.Property(e => e.AdminActionId).HasDefaultValueSql("newsequentialid()");

                entity.HasOne(d => d.PlayerPlayer)
                    .WithMany(p => p.AdminActions)
                    .HasForeignKey(d => d.PlayerPlayerId)
                    .HasConstraintName("FK_dbo.AdminActions_dbo.Player2_Player_PlayerId");

                entity.HasOne(d => d.UserProfile)
                    .WithMany(p => p.AdminActions)
                    .HasForeignKey(d => d.UserProfileId)
                    .HasConstraintName("FK_dbo.AdminActions_dbo.UserProfiles_Id");
            });

            modelBuilder.Entity<BanFileMonitor>(entity =>
            {
                entity.Property(e => e.BanFileMonitorId).HasDefaultValueSql("newsequentialid()");

                entity.HasOne(d => d.GameServerServer)
                    .WithMany(p => p.BanFileMonitors)
                    .HasForeignKey(d => d.GameServerServerId)
                    .HasConstraintName("FK_dbo.BanFileMonitors_dbo.GameServers_GameServer_ServerId");
            });

            modelBuilder.Entity<ChatLog>(entity =>
            {
                entity.Property(e => e.ChatLogId).HasDefaultValueSql("newsequentialid()");

                entity.HasOne(d => d.GameServerServer)
                    .WithMany(p => p.ChatLogs)
                    .HasForeignKey(d => d.GameServerServerId)
                    .HasConstraintName("FK_dbo.ChatLogs_dbo.GameServers_GameServer_ServerId");

                entity.HasOne(d => d.PlayerPlayer)
                    .WithMany(p => p.ChatLogs)
                    .HasForeignKey(d => d.PlayerPlayerId)
                    .HasConstraintName("FK_dbo.ChatLogs_dbo.Player2_Player_PlayerId");
            });

            modelBuilder.Entity<Demo>(entity =>
            {
                entity.Property(e => e.DemoId).HasDefaultValueSql("newsequentialid()");

                entity.HasOne(d => d.UserProfile)
                    .WithMany(p => p.Demos)
                    .HasForeignKey(d => d.UserProfileId)
                    .HasConstraintName("FK_dbo.Demoes_dbo.UserProfiles_Id");
            });

            modelBuilder.Entity<GameServer>(entity =>
            {
                entity.HasKey(e => e.ServerId)
                    .HasName("PK_dbo.GameServers");

                entity.Property(e => e.ServerId).HasDefaultValueSql("newsequentialid()");

                entity.Property(e => e.FtpPort).HasDefaultValueSql("21");

                entity.Property(e => e.LiveLastUpdated).HasDefaultValueSql("'1900-01-01t00:00:00.000'");
            });

            modelBuilder.Entity<GameServerEvent>(entity =>
            {
                entity.Property(e => e.Id).HasDefaultValueSql("newsequentialid()");

                entity.HasOne(d => d.GameServer)
                    .WithMany(p => p.GameServerEvents)
                    .HasForeignKey(d => d.GameServerId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_GameServerEvents_GameServer");
            });

            modelBuilder.Entity<GameServerStat>(entity =>
            {
                entity.Property(e => e.Id).HasDefaultValueSql("newsequentialid()");

                entity.HasOne(d => d.GameServer)
                    .WithMany(p => p.GameServerStats)
                    .HasForeignKey(d => d.GameServerId)
                    .HasConstraintName("FK_GameServerStats_GameServer");
            });

            modelBuilder.Entity<LivePlayer>(entity =>
            {
                entity.Property(e => e.Id).HasDefaultValueSql("newsequentialid()");

                entity.HasOne(d => d.GameServerServer)
                    .WithMany(p => p.LivePlayers)
                    .HasForeignKey(d => d.GameServerServerId)
                    .HasConstraintName("FK_dbo.LivePlayers_dbo.GameServers_GameServer_ServerId");
            });

            modelBuilder.Entity<Map>(entity =>
            {
                entity.Property(e => e.MapId).HasDefaultValueSql("newsequentialid()");
            });

            modelBuilder.Entity<MapVote>(entity =>
            {
                entity.Property(e => e.MapVoteId).HasDefaultValueSql("newsequentialid()");

                entity.HasOne(d => d.MapMap)
                    .WithMany(p => p.MapVotes)
                    .HasForeignKey(d => d.MapMapId)
                    .HasConstraintName("FK_dbo.MapVotes_dbo.Maps_Map_MapId");

                entity.HasOne(d => d.PlayerPlayer)
                    .WithMany(p => p.MapVotes)
                    .HasForeignKey(d => d.PlayerPlayerId)
                    .HasConstraintName("FK_dbo.MapVotes_dbo.Player2_Player_PlayerId");
            });

            modelBuilder.Entity<Player>(entity =>
            {
                entity.Property(e => e.PlayerId).HasDefaultValueSql("newsequentialid()");
            });

            modelBuilder.Entity<PlayerAlias>(entity =>
            {
                entity.Property(e => e.PlayerAliasId).HasDefaultValueSql("newsequentialid()");

                entity.HasOne(d => d.PlayerPlayer)
                    .WithMany(p => p.PlayerAliases)
                    .HasForeignKey(d => d.PlayerPlayerId)
                    .HasConstraintName("FK_dbo.PlayerAlias_dbo.Player2_Player_PlayerId");
            });

            modelBuilder.Entity<PlayerIpAddress>(entity =>
            {
                entity.Property(e => e.PlayerIpAddressId).HasDefaultValueSql("newsequentialid()");

                entity.HasOne(d => d.PlayerPlayer)
                    .WithMany(p => p.PlayerIpAddresses)
                    .HasForeignKey(d => d.PlayerPlayerId)
                    .HasConstraintName("FK_dbo.PlayerIpAddresses_dbo.Player2_Player_PlayerId");
            });

            modelBuilder.Entity<UserProfile>(entity =>
            {
                entity.Property(e => e.Id).HasDefaultValueSql("newsequentialid()");
            });

            modelBuilder.Entity<UserProfileClaim>(entity =>
            {
                entity.Property(e => e.Id).HasDefaultValueSql("newsequentialid()");

                entity.HasOne(d => d.UserProfile)
                    .WithMany(p => p.UserProfileClaims)
                    .HasForeignKey(d => d.UserProfileId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_dbo.UserProfileClaims_dbo.UserProfiles_Id");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}