// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("GameServerServerId", Name = "IX_GameServer_ServerId")]
    public partial class RconMonitor
    {
        [Key]
        public Guid RconMonitorId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastUpdated { get; set; }
        public bool MonitorMapRotation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime MapRotationLastUpdated { get; set; }
        public string LastError { get; set; }
        [Column("GameServer_ServerId")]
        public Guid? GameServerServerId { get; set; }
        [Column("MonitorPlayerIPs")]
        public bool MonitorPlayerIps { get; set; }
        public bool MonitorPlayers { get; set; }

        [ForeignKey("GameServerServerId")]
        [InverseProperty("RconMonitors")]
        public virtual GameServer GameServerServer { get; set; }
    }
}