// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Index("ApplicationUserId", Name = "IX_ApplicationUser_Id")]
    [Index("Timestamp", Name = "IX_Timestamp")]
    public partial class UserLog
    {
        [Key]
        public Guid UserLogId { get; set; }
        public string Message { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Timestamp { get; set; }
        [Column("ApplicationUser_Id")]
        [StringLength(128)]
        public string ApplicationUserId { get; set; }

        [ForeignKey("ApplicationUserId")]
        [InverseProperty("UserLogs")]
        public virtual AspNetUser ApplicationUser { get; set; }
    }
}