// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    public partial class UserProfile
    {
        public UserProfile()
        {
            AdminActions = new HashSet<AdminAction>();
            Demos = new HashSet<Demo>();
            ReportAdminUserProfiles = new HashSet<Report>();
            ReportUserProfiles = new HashSet<Report>();
            UserProfileClaims = new HashSet<UserProfileClaim>();
        }

        [Key]
        public Guid UserProfileId { get; set; }
        [StringLength(50)]
        public string IdentityOid { get; set; }
        [StringLength(50)]
        public string XtremeIdiotsForumId { get; set; }
        [StringLength(128)]
        public string DisplayName { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        [StringLength(128)]
        public string FormattedName { get; set; }
        [StringLength(128)]
        public string PrimaryGroup { get; set; }
        [StringLength(128)]
        public string Email { get; set; }
        public string PhotoUrl { get; set; }
        public string ProfileUrl { get; set; }
        [StringLength(50)]
        public string TimeZone { get; set; }

        [InverseProperty("UserProfile")]
        public virtual ICollection<AdminAction> AdminActions { get; set; }
        [InverseProperty("UserProfile")]
        public virtual ICollection<Demo> Demos { get; set; }
        [InverseProperty("AdminUserProfile")]
        public virtual ICollection<Report> ReportAdminUserProfiles { get; set; }
        [InverseProperty("UserProfile")]
        public virtual ICollection<Report> ReportUserProfiles { get; set; }
        [InverseProperty("UserProfile")]
        public virtual ICollection<UserProfileClaim> UserProfileClaims { get; set; }
    }
}