// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    public partial class UserProfileClaim
    {
        [Key]
        public Guid UserProfileClaimId { get; set; }
        public Guid UserProfileId { get; set; }
        public bool SystemGenerated { get; set; }
        [Required]
        [StringLength(128)]
        public string ClaimType { get; set; }
        [Required]
        public string ClaimValue { get; set; }

        [ForeignKey("UserProfileId")]
        [InverseProperty("UserProfileClaims")]
        public virtual UserProfile UserProfile { get; set; }
    }
}