// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    [Table("UserProfile")]
    public partial class UserProfile
    {
        [Key]
        public Guid Id { get; set; }
        [StringLength(50)]
        public string IdentityOid { get; set; }
        [StringLength(50)]
        public string XtremeIdiotsForumId { get; set; }
    }
}