trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  environment: 'prd'
  location: 'uksouth'
  subscription: 'XI-Pay-As-You-Go'

stages: 
- stage: DeployPortalCorePrd

  jobs:
  - job: DeployPortalCoreBicep
    steps:
      - task: AzureCLI@2
        displayName: DeployPortalCoreBicep
        inputs:
          azureSubscription: $(subscription)
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment sub create `
            --template-file bicep/portalCore.bicep `
            --location $(location) `
            --parameters parLocation=$(location) parEnvironment=$(environment)