trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables: 
  environment: 'prd'
  location: 'uksouth'
  subscription: 'XI-Pay-As-You-Go'
  resourceGroup: 'rg-portal-prd-uksouth-01'
  keyVault: 'kv-portal-prd-uksouth-01'
  appServicePlan: 'plan-portal-prd-uksouth-01'
  appInsights: 'ai-portal-prd-uksouth-01'
  apiManagement: 'apim-portal-prd-uksouth-01'
  serviceBus: 'sb-portal-prd-uksouth-01'
  syncFunctionAppName: 'fn-sync-portal-prd-uksouth-01'

stages:
- stage: Build
  jobs:
  - template: templates/build-function-app.yml
    parameters: 
      jobName: 'BuildSyncFunctionApp'
      projectName: 'sync-func'
      publishArtifact: true

- stage: DeploySyncAppPrd

  jobs:

  - job: DeploySyncAppBicep
    steps:
    - task: AzureCLI@2
      displayName: DeploySyncAppBicep
      inputs:
        azureSubscription: $(subscription)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create --resource-group $(resourceGroup) `
              --template-file bicep/syncApp.bicep  `
              --parameters parLocation=$(location) `
              parEnvironment=$(environment) `
              parKeyVaultName=$(keyVault) `
              parAppServicePlanName=$(appServicePlan) `
              parAppInsightsName=$(appInsights) `
              parApiManagementName=$(apiManagement) `
              parServiceBusName=$(serviceBus)

  - template: templates/deploy-function-app.yml
    parameters:
      dependsOn: ['DeploySyncAppBicep']
      projectName: sync-func
      jobName: DeploySyncFunctionApp
      functionAppName: '$(syncFunctionAppName)'
      functionAppResourceGroup: '$(resourceGroup)'
      environmentServiceNameAzureRM: $(subscription)