trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  environment: 'prd'
  location: 'uksouth'
  subscription: 'XI-Pay-As-You-Go'
  resourceGroup: 'rg-portal-prd-uksouth-01'
  keyVault: 'kv-portal-prd-uksouth-01'
  appServicePlan: 'plan-portal-prd-uksouth-01'
  appInsights: 'ai-portal-prd-uksouth-01'
  apiManagement: 'apim-portal-prd-uksouth-01'
  serversApiName: 'portal-servers-api-prd'
  serversWebAppName: 'webapi-servers-portal-prd-uksouth-01'

stages:
- stage: Build
  jobs:
  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildServersWebApi'
      projectName: 'servers-webapi'
      publishArtifact: true

- stage: DeployServersApiPrd

  jobs:

  - job: DeployServersApiBicep
    steps:
    - task: AzureCLI@2
      displayName: DeployServersApiBicep
      inputs:
        azureSubscription: $(subscription)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $serversApiAppId = (az ad app list --filter "displayName eq '$(serversApiName)'" --query '[].appId') | ConvertFrom-Json
          
          az deployment group create --resource-group $(resourceGroup) `
              --template-file bicep/serversApi.bicep  `
              --parameters parLocation=$(location) `
              parEnvironment=$(environment) `
              parKeyVaultName=$(keyVault) `
              parAppServicePlanName=$(appServicePlan) `
              parAppInsightsName=$(appInsights) `
              parApiManagementName=$(apiManagement) `
              parServersApiAppId=$serversApiAppId

  - template: templates/deploy-web-app.yml
    parameters:
      dependsOn: ['DeployServersApiBicep']
      projectName: servers-webapi
      jobName: DeployServersWebApi
      webAppName: '$(serversWebAppName)'
      webAppNameResourceGroup: '$(resourceGroup)'
      environmentServiceNameAzureRM: $(subscription)
      blueGreenDeploy: true