trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  environment: 'prd'
  location: 'uksouth'
  subscription: 'XI-Pay-As-You-Go'
  resourceGroup: 'rg-portal-prd-uksouth-01'
  keyVault: 'kv-portal-prd-uksouth-01'
  appServicePlan: 'plan-portal-prd-uksouth-01'
  appInsights: 'ai-portal-prd-uksouth-01'
  apiManagement: 'apim-portal-prd-uksouth-01'
  repositoryApiName: 'portal-repository-api-prd'
  repositoryWebAppName: 'webapi-repository-portal-prd-uksouth-01'
  sqlServerName: 'sql-portal-prd-uksouth-01'

stages:
- stage: Build
  jobs:
  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildRepositoryWebApi'
      projectName: 'repository-webapi'
      nugetConfigPath: './src/nuget.config'
      publishArtifact: true

- stage: DeployRepositoryApiPrd

  jobs:

  - job: DeployRepositoryApiBicep
    dependsOn: ['DeployRepositoryAppBicep']
    steps:
    - task: AzureCLI@2
      displayName: DeployRepositoryApiBicep
      inputs:
        azureSubscription: $(subscription)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $repositoryApiAppId = (az ad app list --filter "displayName eq '$(repositoryApiName)'" --query '[].appId') | ConvertFrom-Json
          
          az deployment group create --resource-group $(resourceGroup) `
              --template-file bicep/repositoryApi.bicep  `
              --parameters parLocation=$(location) `
              parEnvironment=$(environment) `
              parKeyVaultName=$(keyVault) `
              parAppServicePlanName=$(appServicePlan) `
              parAppInsightsName=$(appInsights) `
              parApiManagementName=$(apiManagement) `
              parSqlServerName=$(sqlServerName) `
              parRepositoryApiAppId=$repositoryApiAppId

  - template: templates/deploy-web-app.yml
    parameters:
      dependsOn: ['DeployRepositoryApiBicep']
      projectName: repository-webapi
      jobName: DeployRepositoryWebApi
      webAppName: '$(repositoryWebAppName)'
      webAppNameResourceGroup: '$(resourceGroup)'
      environmentServiceNameAzureRM: $(subscription)