trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  environment: 'prd'
  location: 'uksouth'
  subscription: 'XI-Pay-As-You-Go'
  resourceGroup: 'rg-portal-prd-uksouth-01'
  keyVault: 'kv-portal-prd-uksouth-01'
  appServicePlan: 'plan-portal-prd-uksouth-01'
  appInsights: 'ai-portal-prd-uksouth-01'
  apiManagement: 'apim-portal-prd-uksouth-01'
  serviceBus: 'sb-portal-prd-uksouth-01'
  ingestFunctionAppName: 'fn-ingest-portal-prd-uksouth-01'

stages:
- stage: Build
  jobs:
  - template: templates/build-function-app.yml
    parameters: 
      jobName: 'BuildIngestFunctionApp'
      projectName: 'ingest-func'
      publishArtifact: true

- stage: DeployIngestAppPrd

  jobs:

  - job: DeployIngestAppBicep
    steps:
    - task: AzureCLI@2
      displayName: DeployIngestAppBicep
      inputs:
        azureSubscription: $(subscription)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create --resource-group $(resourceGroup) `
              --template-file bicep/ingestApp.bicep `
              --parameters parLocation=$(location) `
              parEnvironment=$(environment) `
              parKeyVaultName=$(keyVault) `
              parAppServicePlanName=$(appServicePlan) `
              parAppInsightsName=$(appInsights) `
              parApiManagementName=$(apiManagement) `
              parServiceBusName=$(serviceBus)

  - template: templates/deploy-function-app.yml
    parameters:
      dependsOn: ['DeployIngestAppBicep']
      projectName: ingest-func
      jobName: DeployIngestFunctionApp
      functionAppName: '$(ingestFunctionAppName)'
      environmentServiceNameAzureRM: $(subscription)