trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - template: templates/build-function-app.yml
    parameters: 
      jobName: 'BuildSyncFunctionApp'
      projectName: 'sync-func'
      publishArtifact: true

- stage: DeploySyncAppPrd

  variables: 
    environment: 'prd'
    region: 'uksouth'
    instance: '01'
    AzSubscription: 'XI-Pay-As-You-Go'

  jobs:

  - job: DeploySyncAppBicep
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'XI-Pay-As-You-Go'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create `
          --resource-group 'rg-portal-prd-uksouth-01' `
          --template-file bicep/syncApp.bicep  `
          --parameters parLocation='uksouth' parEnvironment='prd' parKeyVaultName='kv-portal-prd-uksouth-01' parFuncAppServicePlanName='plan-fn-portal-prd-uksouth-01' parAppInsightsName='ai-portal-prd-uksouth-01' parApiManagementName='apim-portal-prd-uksouth-01' parServiceBusName='sb-portal-prd-uksouth-01'

  - template: templates/deploy-function-app.yml
    parameters:
      projectName: sync-func
      jobName: DeploySyncFunctionApp
      functionAppName: 'fn-sync-portal-$(environment)-$(region)-$(instance)'
      environmentServiceNameAzureRM: 'XI-Pay-As-You-Go'