trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildRepositoryWebApi'
      projectName: 'repository-webapi'
      nugetConfigPath: './src/nuget.config'
      publishArtifact: true

- stage: DeployRepositoryApiPrd

  variables: 
    environment: 'prd'
    region: 'uksouth'
    instance: '01'
    AzSubscription: 'XI-Pay-As-You-Go'

  jobs:

  - job: DeployRepositoryApiBicep
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'XI-Pay-As-You-Go'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $repositoryApiAppName = 'portal-repository-api-prd'
          $repositoryApiAppId = (az ad app list --filter "displayName eq '$repositoryApiAppName'" --query '[].appId') | ConvertFrom-Json

          az deployment group create `
          --resource-group 'rg-portal-prd-uksouth-01' `
          --template-file bicep/repositoryApi.bicep  `
          --parameters parLocation='uksouth' parEnvironment='prd' parKeyVaultName='kv-portal-prd-uksouth-01' parAppServicePlanName='plan-portal-prd-uksouth-01' parAppInsightsName='ai-portal-prd-uksouth-01' parApiManagementName='apim-portal-prd-uksouth-01' parRepositoryApiAppId=$repositoryApiAppId

  - template: templates/deploy-web-app.yml
    parameters:
      projectName: repository-webapi
      jobName: DeployRepositoryWebApp
      webAppName: 'webapi-repository-portal-$(environment)-$(region)-$(instance)'
      webAppNameResourceGroup: 'rg-portal-$(environment)-$(region)-$(instance)'
      environmentServiceNameAzureRM: 'XI-Pay-As-You-Go'