trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  environment: 'prd'
  location: 'uksouth'
  subscription: 'XI-Pay-As-You-Go'
  resourceGroup: 'rg-portal-prd-uksouth-01'
  keyVault: 'kv-portal-prd-uksouth-01'
  appServicePlan: 'plan-portal-prd-uksouth-01'
  appInsights: 'ai-portal-prd-uksouth-01'
  apiManagement: 'apim-portal-prd-uksouth-01'
  serviceBus: 'sb-portal-prd-uksouth-01'
  eventsApiAppName: 'portal-events-api-prd'
  eventsFunctionAppName: 'fn-events-portal-prd-uksouth-01'

stages:
- stage: Build
  jobs:
  - template: templates/build-function-app.yml
    parameters: 
      jobName: 'BuildEventsFunctionApp'
      projectName: 'events-func'
      publishArtifact: true

- stage: DeployEventsAppPrd

  jobs:

  - job: DeployEventsAppBicep
    steps:
    - task: AzureCLI@2
      displayName: DeployEventsAppBicep
      inputs:
        azureSubscription: $(subscription)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $eventsApiAppId = (az ad app list --filter "displayName eq '$(eventsApiAppName)'" --query '[].appId') | ConvertFrom-Json

          az deployment group create --resource-group $(resourceGroup) `
              --template-file bicep/eventsApp.bicep  `
              --parameters parLocation=$(location) `
              parEnvironment=$(environment) `
              parKeyVaultName=$(keyVault) `
              parAppServicePlanName=$(appServicePlan) `
              parAppInsightsName=$(appInsights) `
              parApiManagementName=$(apiManagement) `
              parServiceBusName=$(serviceBus) `
              parEventsApiAppId=$eventsApiAppId

  - template: templates/deploy-function-app.yml
    parameters:
      dependsOn: ['DeployEventsAppBicep']
      projectName: events-func
      jobName: DeployEventsFunctionApp
      functionAppName: '$(eventsFunctionAppName)'
      functionAppResourceGroup: '$(resourceGroup)'
      environmentServiceNameAzureRM: $(subscription)
      blueGreenDeploy: true