trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - template: templates/build-function-app.yml
    parameters: 
      jobName: 'BuildEventsFunctionApp'
      projectName: 'events-func'
      publishArtifact: true

- stage: DeployEventsApiPrd

  variables: 
    environment: 'prd'
    region: 'uksouth'
    instance: '01'
    AzSubscription: 'XI-Pay-As-You-Go'

  jobs:

  - job: DeployEventsApiBicep
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(AzSubscription)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $eventsApiName = 'portal-events-api-prd'
          $eventsApiAppId = (az ad app list --filter "displayName eq '$eventsApiName'" --query '[].appId') | ConvertFrom-Json

          az deployment group create `
          --resource-group 'rg-portal-prd-uksouth-01' `
          --template-file bicep/eventsApi.bicep  `
          --parameters parLocation='uksouth' parEnvironment='prd' parKeyVaultName='kv-portal-prd-uksouth-01' parFuncAppServicePlanName='plan-fn-portal-prd-uksouth-01' parAppInsightsName='ai-portal-prd-uksouth-01' parApiManagementName='apim-portal-prd-uksouth-01' parServiceBusName='sb-portal-prd-uksouth-01' parEventsApiAppId=$eventsApiAppId

  - template: templates/deploy-function-app.yml
    parameters:
      projectName: events-func
      jobName: DeployEventsFunctionApp
      functionAppName: 'fn-events-portal-$(environment)-$(region)-$(instance)'
      environmentServiceNameAzureRM: '$(AzSubscription)'