trigger:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pr:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pool: 'Dedicated'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

variables:
  buildConfiguration: 'Release'

stages: 
- stage: Build
  jobs:

  #- template: jobs/dependency-check.yml@ado-pipeline-templates
  #  parameters: 
  #    jobName: 'DependencyCheck'
  #    failOnCVSS: 4

  - template: jobs/build-net-core-projects.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildNetCoreProjects'
      buildConfiguration: $(buildConfiguration)
      additionalBuildSteps:
      - task: DotNetCoreCLI@2
        displayName: 'Publish admin-webapp project'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/admin-webapp.csproj'
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/admin-webapp.zip'
      - task: ArchiveFiles@2
        displayName: "Package sync-func project"
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/src/function-apps/sync-func/bin/Release/net6.0/'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/sync-func.zip'
      additionalPublishSteps: 
      - publish: '$(Build.artifactStagingDirectory)/admin-webapp.zip'
        displayName: 'Publish admin-webapp artifact'
        artifact: admin-webapp
      - publish: '$(Build.artifactStagingDirectory)/sync-func.zip'
        displayName: 'Publish sync-func artifact'
        artifact: sync-func

  - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BicepLinter'
      azureSubscription: 'spn-ado-XtremeIdiots-Public-devtest'

  - template: templates/bicep-environment-validation.yml
    parameters:
      dependsOn: [BicepLinter]
      azureSubscription: 'spn-ado-XtremeIdiots-Public-portal-prd'
      environment: 'xtremeidiots-portal-prd'
      environmentName: 'Prd'
      environmentTag: 'prd'

- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  - template: templates/deploy-environment.yml
    parameters:
      azureSubscription: 'spn-ado-XtremeIdiots-Public-portal-prd'
      environment: 'xtremeidiots-portal-prd'
      environmentName: 'Prd'
      environmentTag: 'prd'
      webAppsAzureSubscription: 'spn-ado-XtremeIdiots-Public-portal-prd-webapps'
      webAppsEnvironment: 'platform-webapps-prd-uksouth'
      webAppsResourceGroup: 'rg-platform-webapps-prd-uksouth'
      blueGreenDeploy: false