parameters:
- name: skipBicepValidate
  type: boolean
  default: false

trigger:
  branches:
    include:
    - main
    - feature/*
    - dependabot/*

pr:
  branches:
    include:
    - main
    - feature/*
    - dependabot/*

schedules:
  - cron: "0 3 * * 0"
    displayName: Weekly Build
    branches:
      include:
      - main

pool: 'Dedicated'

stages: 
- stage: Build
  jobs:
  - template: templates/dependency-check.yml
    parameters: 
      jobName: 'DependencyCheck'
      failOnCVSS: 4

  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildAdminWebApp'
      projectName: 'admin-webapp'
      nugetConfigPath: './src/nuget.config'

  - template: templates/build-function-app.yml
    parameters: 
      jobName: 'BuildEventsFunctionApp'
      projectName: 'events-func'

  - template: templates/build-function-app.yml
    parameters: 
      jobName: 'BuildIngestFunctionApp'
      projectName: 'ingest-func'

  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildRepositoryWebApi'
      projectName: 'repository-webapi'
      nugetConfigPath: './src/nuget.config'

  - template: templates/build-function-app.yml
    parameters: 
      jobName: 'BuildRepositoryFunctionApp'
      projectName: 'repository-func'
      nugetConfigPath: './src/nuget.config'

  - template: templates/build-function-app.yml
    parameters: 
      jobName: 'BuildSyncFunctionApp'
      projectName: 'sync-func'

  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildServersWebApi'
      projectName: 'servers-webapi'

  - template: templates/build-sql-database.yml

- stage: ValidateBicep
  jobs: 
  - job: LintCode
    displayName: Lint Code
    steps:
      - script: |
          az bicep build --file bicep/platform.bicep
          az bicep build --file bicep/services.bicep
        name: LintBicepCode
        displayName: Run Bicep Linter

  - deployment: ValidateBicepCode
    dependsOn: [LintCode]
    environment: 'xtremeidiots-portal-prd'
    
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              name: RunPreflightValidation
              inputs:
                azureSubscription: 'spn-ado-XtremeIdiots-Public-xtremeidiots-portal-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub validate `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.prd.json

                  if ('${{ parameters.skipBicepValidate }}' -eq $false)
                  {
                    az deployment group validate `
                      --resource-group 'rg-portal-prd-uksouth' `
                      --template-file bicep/services.bicep `
                      --parameters @params/services.prd.json `
                      parEventsApiAppId=00000000-0000-0000-0000-000000000000 `
                      parRepositoryApiAppId=00000000-0000-0000-0000-000000000000 `
                      parServersApiAppId=00000000-0000-0000-0000-000000000000
                  }

            - task: AzureCLI@2
              name: RunWhatIfDeploy
              inputs:
                azureSubscription: 'spn-ado-XtremeIdiots-Public-xtremeidiots-portal-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub what-if `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.prd.json

                  if ('${{ parameters.skipBicepValidate }}' -eq $false)
                  {
                    az deployment group what-if `
                      --resource-group 'rg-portal-prd-uksouth' `
                      --template-file bicep/services.bicep `
                      --parameters @params/services.prd.json `
                      parEventsApiAppId=00000000-0000-0000-0000-000000000000 `
                      parRepositoryApiAppId=00000000-0000-0000-0000-000000000000 `
                      parServersApiAppId=00000000-0000-0000-0000-000000000000
                  }