name: Merge To Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for Az CLI Login
  contents: read # This is required for actions/checkout

jobs:
  dotnet-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: frasermolyneux/actions/dotnet-web-ci@main
      with:
        dotnet-project: "admin-webapp"
        dotnet-version: 7.0.x
        src-folder: "src"
